apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: spring-boot-jwt
  name: springbootjwt
spec:
  replicas: 1
  selector:
    matchLabels:
      name: spring-boot-jwt
  template:
    metadata:
      labels:
        name: spring-boot-jwt
    spec:
      containers:
        - name: spring-boot-jwt
          image: santhoshm/spring-boot-jwt
          ports:
            - containerPort: 8080
              protocol: TCP
              name: http
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: spring-boot-jwt
  name: spring-boot-jwt
spec:
  type: LoadBalancer
  ports:
    - port: 9999
      targetPort: 8080
      protocol: TCP
      name: http      
  selector:
    name: spring-boot-jwt
