apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: spring-boot-jwt
  name: springbootjwt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-jwt
  template:
    metadata:
      labels:
        app: spring-boot-jwt
    spec:
      containers:
        - name: spring-boot-jwt
          image: santhoshm/spring-boot-jwt
          ports:
            - containerPort: 8080
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: spring-boot-jwt
  name: spring-boot-jwt
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: spring-boot-jwt
