apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: spring-boot-jwt
  name: spring-boot-jwt
spec:
  replicas: 1
  selector:
    matchLabels:
      name: spring-boot-jwt
  template:
    metadata:
      labels:
        name: spring-boot-jwt
    spec:
      containers:
        - name: spring-boot-jwt
          image: santhoshm/spring-boot-jwt
          ports:
            - containerPort: 8080
              protocol: TCP
              name: http
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: spring-boot-jwt
  name: spring-boot-jwt
spec:
  type: ClusterIP
  ports:
    - port: 9999
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    name: spring-boot-jwt
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jwt-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx	
  rules:
  - http:
      paths:
      - path: /hello
        pathType: Prefix
        backend:
          service:
            name: spring-boot-jwt
            port:
              number: 9999
